"""
PROJECT SENTINEL — HOOD Zero-Day Defense & Patch Engine
Coordinates vulnerability response, candidate patch development in isolation,
and multi-layer verification (Developer -> X Red Team -> Independent Validator).
Governed by Master System Specification v1.3 Sections 8, 9 & 10.
"""

from __future__ import annotations
import difflib
from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime, timezone

from services.sentinel.contracts import (
    SentinelFinding,
    PatchCandidate,
    FindingStatus,
    FindingSeverity
)
from services.sentinel.x_red_team import IndependentValidationRunner


class PatchEngine:
    """Orchestrates candidate patch development, verification layers, and safe deployment."""

    def __init__(self, patches_dir: Optional[Path] = None):
        self.patches_dir = patches_dir or Path("artifacts/sentinel_patches")
        self.patches_dir.mkdir(parents=True, exist_ok=True)
        self.candidates: Dict[str, PatchCandidate] = {}

    def generate_candidate_patch(
        self,
        finding: SentinelFinding,
        original_code: str,
        remediated_code: str,
        root_cause: str,
        remediation_summary: str,
        regression_tests: List[str]
    ) -> PatchCandidate:
        """Creates an isolated candidate patch with diff and regression tests."""
        # Generate unified diff
        diff_lines = list(difflib.unified_diff(
            original_code.splitlines(keepends=True),
            remediated_code.splitlines(keepends=True),
            fromfile=f"a/{finding.affected_component}",
            tofile=f"b/{finding.affected_component}"
        ))
        diff_text = "".join(diff_lines)

        patch = PatchCandidate(
            finding_id=finding.finding_id,
            affected_component=finding.affected_component,
            root_cause=root_cause,
            remediation_summary=remediation_summary,
            patch_diff=diff_text,
            regression_tests_created=regression_tests,
            layer1_developer_passed=True,  # Generated by developer layer
            approval_required=True,
            is_approved=False,
            is_deployed=False
        )

        self.candidates[patch.patch_id] = patch
        return patch

    def verify_candidate_patch(
        self,
        patch_id: str,
        unpatched_probe_result: bool,
        patched_probe_result: bool,
        regression_suite_result: bool
    ) -> Dict[str, Any]:
        """Runs Layer 3 Independent Verification on candidate patch."""
        patch = self.candidates.get(patch_id)
        if not patch:
            raise KeyError(f"Patch {patch_id} not found.")

        validation = IndependentValidationRunner.verify_patch(
            unpatched_probe=lambda: unpatched_probe_result,
            patched_probe=lambda: patched_probe_result,
            regression_test_func=lambda: regression_suite_result
        )

        if validation["verified"]:
            patch.layer3_independent_validator_passed = True

        return validation

    def record_owner_approval(self, patch_id: str, approved_by: str) -> bool:
        """Records explicit Root Owner approval before production deployment."""
        if approved_by != "zack" and approved_by != "Zak":
            raise PermissionError("Only ZACK (Root Owner) can approve patch deployments.")

        patch = self.candidates.get(patch_id)
        if not patch:
            raise KeyError(f"Patch {patch_id} not found.")

        if not patch.layer3_independent_validator_passed:
            raise ValueError("Cannot approve patch that has not passed Layer 3 Independent Verification.")

        patch.is_approved = True
        return True

    def deploy_patch(self, patch_id: str, target_file: Path, remediated_code: str) -> Dict[str, Any]:
        """Deploys approved patch to target file with automatic rollback capability."""
        patch = self.candidates.get(patch_id)
        if not patch:
            raise KeyError(f"Patch {patch_id} not found.")

        if not patch.is_approved:
            raise PermissionError(f"Deployment blocked: Patch {patch_id} has not received Root Owner approval.")

        # Backup existing target
        backup_path = self.patches_dir / f"{target_file.name}.bak_{patch.patch_id}"
        if target_file.exists():
            backup_path.write_bytes(target_file.read_bytes())

        try:
            target_file.write_text(remediated_code, encoding="utf-8")
            patch.is_deployed = True
            patch.deployed_at = datetime.now(timezone.utc).isoformat()
            return {
                "status": "DEPLOYED",
                "patch_id": patch_id,
                "target_file": str(target_file),
                "backup_file": str(backup_path)
            }
        except Exception as e:
            # Rollback
            if backup_path.exists():
                target_file.write_bytes(backup_path.read_bytes())
            raise RuntimeError(f"Deployment failed, rolled back to original: {str(e)}")
